### PR TITLE
dev-tim

### PR DESCRIPTION
**Pull request by timomer**
Updates to UI, etc

### CODE REVIEW

**Comment by timomer** [comment]
Hey @GeoffWyche, ok, slowly getting there with these PRs ;)

This update is mostly UI, in summary...
- Added shared Prefs for app settings
- Added Toolbar and menu to MainActivity
- Added MainApp.class as the main class for the app, a place to put shared variables / functions 
- Added RileyLinkScan.class to scan for devices and store in Prefs (this is not passed to your service just yet)
- Misc icons and Strings, etc

Not all items on the Menu will work just yet, next PR will be adding the RT2 Service class and cleaning up MainActivity - wanted to keep that for a new PR so you can easily review. 

Once accepted you should be able to build the app from this branch and review, if all looks ok merge with master.

**Comment by GeoffWyche** [comment]
Hrm... still need to get used to "build the dev-tim branch before merging with master".  I just merged without looking.  Hopefully all will be well.

**Comment by GeoffWyche** [comment]
Looks like all went well -- thanks!

**Comment by timomer** [comment]
great, should get another PR done later today!

**Pull request merged**
